#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	Motors Power Levels:
	127 = Full power clockwise
	-127 = Full power backwards
	0 = Stationary
	Servo Positionioning:
	360 = Positive Degrees positioning on a circle
	-360 = Negative degrees positioning on a circle
	0 = Middle
	Binary:
	0 = OFF
	1 = ON
	Motors & Servos Ports:
	port1 = Unused
	port2 = Left Wheel
	port3 = Right Wheel
	port4 = Linear Arm Motor
	port5 = Left Claw Servo
	port6 = Right Claw Servo
	port 7 = Bulldozer Attachment Servo 1
	port 8 = Vulldozer Attachment Servo 2
	Note: vexRT[] refers to the VEX Joystick's channels (there are up to 8 channels on the joystick).
	*/


		int a = 0;
		int b = 0;
		int c = 0;

	// Infinite while loop to continiously run the robot
	while(1 == 1) {
		while(vexRT[Ch3] > 10 || vexRT[Ch3] < -10) {
			motor[port2] = -(vexRT[Ch3]); // Channel 3 (left-side joystick, up & down) for the left wheel
		}
		while(vexRT[Ch2] > 10 || vexRT[Ch2] < -10) {
			motor[port3] = (vexRT[Ch2]); // Channel 2 (right-side joystick, up & down) for the right wheel
		}
		while(vexRT[Ch4] > 10 || vexRT[Ch4] < -10) {
			motor[port4] = (vexRT[Ch4]); // Channel 4 (left-side joystick, left & right) for the linear arm
		}
		while(vexRT[Ch1] > 10 || vexRT[Ch1] < -10) {
			motor[port7] = (vexRT[Ch1]); // Channel 1 (right-side joystick, left & right) for the bulldozer
		}


		//Claw Servos

		if (vexRT[Btn5U] == 1 && vexRT[Btn5U] != 0 && a < 127 && a > -128) {// Holding Channel 5 Up Button
			a = a + 1;
			motor[port5] = a; // Port 5 Motor closes left claw
		}
		while (vexRT[Btn5D] == 1 && vexRT[Btn5D] != 0 && a < 127 && a > -127) {// Holding Channel 5 Down Button
			a = a - 1;
			motor[port5] = a; // Port 5 Motor opens left claw
		}
		if(vexRT[Btn8L] == 1) {
			a = 0;
			motor[port5] = a;
		}

		while (vexRT[Btn6U] == 1 && vexRT[Btn6U] != 0 && b < 127 && b > -127) {// Holding Channel 6 Up Button
			b = b - 1;
			motor[port6] = b; // Port 6 Motor closes right claw
		}
		while(vexRT[Btn6D] == 1 && vexRT[Btn6D] != 0 && b < 127 && b > -127) {// Holding Channel 6 Down Button
			b = b + 1;
			motor[port6] = b; // Port 6 Motor opens right claw
		}
		if(vexRT[Btn8R] == 1) {
			b = 0;
			motor[port6] = b;
		}



		// Bulldozer servo


		while (vexRT[Btn8U] == 1 && vexRT[Btn8U] != 0 && c < 127 && c > -127) {// Holding Channel 8 Up Button
			c = c + 1;
			motor[port8] = c; // Port 6 Motor lifts bulldozer servo
		}
		while(vexRT[Btn8D] == 1 && vexRT[Btn8D] != 0 && c < 127 && c > -127) {// Holding Channel 8 Down Button
			c = c - 1;
			motor[port8] = c; // Port 6 Motor lowers bulldozer servo
		}
		if(vexRT[Btn7D] == 1) {
			c = 0;
			motor[port8] = c;
		}


		//Autonomous
		if (vexRT[Btn7U] == 1) {
			delay(2000); //Delay to give driver time to set gamepad down

			motor[port2] = 50; //Move Backward for 2 seconds to enter autonomous zone
			motor[port3] = -50;
			wait1Msec(2000);

			motor[port7] = 127; //Pick up bulldozer for 0.75 seconds
			motor[port8] = -127;
			wait1Msec(750);

			motor[port2] = -50; //Move Forward for 3 seconds to move out of autonomous zone
			motor[port3] = 50;
			wait1Msec(4000);

			motor[port2] = 100; // Turn for 1 seconds
			motor[port3] = 0;
			wait1Msec(1000);

			motor[port2] = -100; //Move Forward for 3 secods to appraoach trailer
			motor[port3] = 100;
			wait1Msec(3000);

			motor[port2] = 0; //Stop motors, return bulldozer, and end autonomous
			motor[port3] = 0;
			motor[port7] = 0;
			motor[port8] = 0;
			delay(5000);
		} // End If statement for autonomous

	} // End while loop


} // End main task function
